package cricketleagueanalysis;

public enum SortedDataBaseOnField {
    BATSMAN_AVERAGE, STRIKING_RATE, BY_4s_AND_6s, STRIKING_RATE_WITH_6S_And_4s, AVERAGE_WITH_BEST_STRIKING_RATE,
    MAXIMUM_RUN_WITH_AVERAGE, BOWLER_AVERAGE,STRIKING_RATE_BOWLER,ECONOMY,BY_4w_AND_5w,AVERAGE_WITH_BEST_STRIKING_RATE_BOWLER,
    MAXIMUM_WICKET_WITH_AVERAGE,BEST_BOWLING_BATTING_AVERAGE,BEST_ALL_ROUNDER;
}
