package cricketleagueanalysis;

public enum SortedDataBaseOnBatsmanField {
    AVERAGE_BATSMAN, STRIKING_RATE, BY_4s_AND_6s, STRIKING_RATE_WITH_6S_And_4s, AVERAGE_WITH_BEST_STRIKING_RATE,
    MAXIMUM_RUN_WITH_AVERAGE, AVERAGE_BOWLER,STRIKING_RATE_BOWLER,ECONOMY,BY_4w_AND_5w;
}
